/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis5;

/**
 *
 * @author Asus
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        Disc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hb1 = new javax.swing.JTextField();
        hb3 = new javax.swing.JTextField();
        hb4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        hb2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Keluar");
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 330, 73, 40);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 400, 250, 130);

        Disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscActionPerformed(evt);
            }
        });
        getContentPane().add(Disc);
        Disc.setBounds(230, 280, 120, 30);

        jLabel2.setText("          Pembayaran ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 10, 150, 40);

        jLabel3.setText("Harga barang 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 70, 110, 30);

        jLabel4.setText("Harga barang 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 110, 100, 40);

        jLabel5.setText("Harga barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 130, 30);

        jLabel7.setText("Diskon");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 270, 70, 40);

        hb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb1ActionPerformed(evt);
            }
        });
        getContentPane().add(hb1);
        hb1.setBounds(230, 70, 120, 30);
        getContentPane().add(hb3);
        hb3.setBounds(230, 170, 120, 30);
        getContentPane().add(hb4);
        hb4.setBounds(230, 220, 120, 30);

        jLabel6.setText("Harga barang 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 160, 120, 40);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(60, 330, 90, 40);

        hapus.setText("Hapus ");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(170, 330, 73, 40);

        hb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb2ActionPerformed(evt);
            }
        });
        getContentPane().add(hb2);
        hb2.setBounds(230, 120, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscActionPerformed

    private void hb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hb1ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        int hargabarang1 = Integer.parseInt(hb1.getText());
        int hargabarang2 = Integer.parseInt(hb2.getText());
        int hargabarang3 = Integer.parseInt(hb3.getText());
        int hargabarang4 = Integer.parseInt(hb4.getText());
        int  diskon = Integer.parseInt(Disc.getText());
        int total;
        int  total_bayar;
        int harga;

        harga = hargabarang1+hargabarang2+hargabarang3+hargabarang4;

        if(diskon == 0){
            total = harga;
        }
        else {
            total_bayar = harga*diskon/100;
            total = harga - total_bayar;
        }
        TA.setText("harga barang 1: "+hargabarang1+"\nharga barang 2: "+hargabarang2+"\nharga barang 3: "+hargabarang3+"\nharga barang 4 : "+hargabarang4+
            "\ndiskon : "+diskon+"\nharga: "+harga+"\ntotal: "+total);
    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        TA.setText("");
        hb1.setText("");
        hb2.setText("");
        hb3.setText("");
        hb4.setText("");
        Disc.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void hb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Disc;
    private javax.swing.JTextArea TA;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hb1;
    private javax.swing.JTextField hb2;
    private javax.swing.JTextField hb3;
    private javax.swing.JTextField hb4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
